algoliasearch:
  api_key: process.env.ALGOLIA_API_KEY
  app_id: process.env.ALGOLIA_APP_ID
  index: dev_windsurf
bellini_api:
  key: process.env.WRAPAPI_KEY
bigsurfshop_api:
  key: process.env.WRAPAPI_KEY
buffer:
  access_token: process.env.BUFFER_ACCESS_TOKEN
  accounts:
    facebook: 5871279baa70e81d3a6389bf
    twitter: 58ed8477d05bd37d4c46d326
check_hosts:
  bellini:
    - 'https://wrapapi.com'
    - 'http://www.bellini.es'
  bigsurfshop:
    - 'https://wrapapi.com'
    - 'http://www.bigsurfshop.com'
  easysurfshop:
    - 'https://wrapapi.com'
    - 'https://easy-surfshop.com'
  lpwind:
    - 'https://wrapapi.com'
    - 'http://www.lpwindsurf.com'
  ozutarifa:
    - 'https://wrapapi.com'
    - 'http://ozu-tarifa.com'
  surfkeppler:
    - 'https://wrapapi.com'
    - 'https://www.surfkeppler.de'
  telstarsurf:
    - 'https://wrapapi.com'
    - 'http://www.telstarsurf.com'
  totalwind:
    - 'https://wrapapi.com'
    - 'http://totalwind.net/foro'
  wewind:
    - 'https://wrapapi.com'
    - 'http://we-wind.com'
easysurfshop_api:
  key: process.env.WRAPAPI_KEY
lpwind_api:
  key: process.env.WRAPAPI_KEY
ozutarifa_api:
  key: process.env.WRAPAPI_KEY
redis: process.env.REDIS_URL
surfkeppler_api:
  key: process.env.WRAPAPI_KEY
telstarsurf_api:
  key: process.env.WRAPAPI_KEY
totalwind_api:
  key: process.env.WRAPAPI_KEY
  pages: 5
  start: 2
wewind_api:
  key: process.env.WRAPAPI_KEY
premium_providers:
  - bellini
  - easysurfshop
  - lpwind
  - wewind
share:
  minPriceScore: 90
  fallbackImage: 'https://blog.windtoday.co/logo.jpg'
